# Generated by Django 4.0.4 on 2022-08-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_companys',
            name='fy_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
