# Generated by Django 4.0.4 on 2022-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_create_companys_fy_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_companys',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
