# Generated by Django 4.0.4 on 2022-08-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_create_companys_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.create_companys'),
        ),
    ]
