# Generated by Django 4.0.4 on 2022-08-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_cost_create_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tally_ledger',
            name='company',
        ),
    ]
