# Generated by Django 4.0.4 on 2022-08-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_tally_ledger_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_group'),
        ),
    ]
