# Generated by Django 4.0.4 on 2022-08-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_gst_lutbond_validity_from_gst_lutbond_validity_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_companys',
            new_name='Companies',
        ),
    ]
