# Generated by Django 4.0.4 on 2022-08-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_create_companys_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='base_cur',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='bks_begining',
            new_name='books_begin',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='c_address1',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='c_country',
            new_name='currency_symbol',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='fy_begning',
            new_name='fin_begin',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='fy_end',
            new_name='fin_end',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='c_name',
            new_name='formal_name',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='c_state',
            new_name='mailing_name',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='frml_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='m_name',
            new_name='state',
        ),
    ]
