# Generated by Django 4.0.4 on 2022-08-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_cost_center_rateofexchange_voucher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='POSInvoice',
            new_name='default_bank',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='allocation',
            new_name='enable_acc',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='journal',
            new_name='manu_jrnl',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='defaultBank',
            new_name='msg_1',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='message1',
            new_name='msg_2',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='message2',
            new_name='pos_invoice',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='printVoucher',
            new_name='prnt_VA_save',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='purchase',
            new_name='title_print',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='titlePrint',
            new_name='track_purchase',
        ),
    ]
