# Generated by Django 4.0.4 on 2022-08-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_employee_e_found_trasfer_add_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_payhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('pay_type', models.CharField(max_length=225)),
                ('income_type', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('affect_net', models.CharField(max_length=225)),
                ('payslip', models.CharField(max_length=225)),
                ('calculation_of_gratuity', models.CharField(max_length=225)),
                ('cal_type', models.CharField(max_length=225)),
                ('calculation_period', models.CharField(max_length=225)),
                ('leave_withpay', models.CharField(max_length=225)),
                ('leave_with_out_pay', models.CharField(max_length=225)),
                ('production_type', models.CharField(max_length=225)),
                ('opening_balance', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('effective', models.CharField(max_length=225)),
                ('payhead', models.CharField(max_length=225)),
                ('rate', models.CharField(max_length=225)),
                ('per', models.CharField(max_length=225)),
                ('pay_type', models.CharField(max_length=225)),
                ('cal_type', models.CharField(max_length=225)),
            ],
        ),
    ]
