# Generated by Django 4.0.4 on 2022-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('period', models.CharField(blank=True, default='null', max_length=225)),
                ('units', models.CharField(blank=True, default='null', max_length=225)),
            ],
        ),
    ]
