# Generated by Django 4.0.4 on 2022-08-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_emp_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_employeegroup',
            name='cat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.emp_category'),
        ),
    ]
