# Generated by Django 4.0.4 on 2022-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_create_employeegroup_cat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='uqc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_uqc', models.CharField(max_length=225)),
            ],
        ),
    ]
