# Generated by Django 4.0.4 on 2022-09-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_uqc'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='uqc1',
            field=models.CharField(blank=True, default='null', max_length=225),
        ),
    ]
